server:
  port: 8080

spring:
  application:
    name: corp-portal-core
  jpa:
    database: postgresql
    open-in-view: false
    hibernate:
      ddl-auto: create
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/corp-portal-core
    username: postgres
    password: postgres
    hikari:
      schema: core_schema
      connection-init-sql: CREATE schema if not exists core_schema
      connection-timeout: 10000