server:
  port: 8080

spring:
  application:
    name: corp-portal-core
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yml
  #  cloud:
  #    config:
  #      uri: http://localhost:8071

  jpa:
    database: postgresql
    open-in-view: false
    hibernate:
      ddl-auto: none
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/corp-portal-core
    username: postgres
    password: postgres
    hikari:
      schema: core_schema
      connection-init-sql: CREATE schema if not exists core_schema
      connection-timeout: 10000
logging:
  level:
    sql: debug
#eureka:
#  instance:
#    preferIpAddress: true
#  client:
#    registerWithEureka: true
#    fetchRegistry: true
#    serviceUrl:
#      defaultZone: http://localhost:8070/eureka/
