spring:
  application:
    name: corp-portal-config
  profiles:
    active: native

  cloud:
    config:
      server:
        native:
          search-locations: classpath:/config


#  profiles:
#    active:
#      - vault
#  cloud:
#    config:
#      server:
#        vault:
#          kv-version: 2
#          default-key: dev # secret
#          backend: corp-portal-core # name secret engine
#    vault:
#      host: localhost
#      port: 8200
#      scheme: http
#      uri: http://localhost:8200
#      connection-timeout: 5000
#      read-timeout: 15000
#      authentication: none
#  config:
#    import: vault://

server:
  port: 8071