--liquibase formatted sql
--changeset author:andrei_shev
--preconditions onFail:CONTINUE onError:CONTINUE
--precondition-sql-check expectedResult:0 SELECT COUNT(*) FROM core_schema.company

CREATE TABLE core_schema.company (
                                     id int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
                                     subsidiary_company bool NULL,
                                     "name" varchar(254) NULL,
                                     CONSTRAINT company_name_key UNIQUE ("name"),
                                     CONSTRAINT company_pkey PRIMARY KEY (id)
);